# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: actonit-server_development

test:
  <<: *default
  database: actonit-server_test

staging:
  <<: *default
  database: actonit-server_staging
  username: actonit-server
  password: <%= ENV['ACTONIT-SERVER_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: actonit-server_production
  username: actonit-server
  password: <%= ENV['ACTONIT-SERVER_DATABASE_PASSWORD'] %>
